set(CTEST_SITE "babycakes.lbl.gov")
set(CTEST_BUILD_NAME "MacOSX10.8.2-gcc4.2.1")
set(CTEST_DASHBOARD_ROOT "/Users/bloring/visit/dashboards")
set(CONFIG_SITE ${CTEST_DASHBOARD_ROOT}/visit-deps/babycakes.cmake)
set(TEST_WARNINGS "-Wall -Wno-overloaded-virtual -Wno-unused-function -Wno-sign-compare -Wno-unused-variable -Wno-write-strings -Wno-parentheses -Wno-missing-braces")
set(CTEST_BUILD_CONFIGURATION Debug)
set(CTEST_SVN_COMMAND "/usr/bin/svn")
set(CTEST_TEST_ARGS PARALLEL_LEVEL 4)
set(CTEST_BUILD_FLAGS -j16)
include("${CTEST_DASHBOARD_ROOT}/visit-dashboard.cmake")
